spring:
  datasource:
    url: jdbc:mysql://rm-uf6l6456lwm0sej7uo.mysql.rds.aliyuncs.com:3306/batch_task?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ly_ds
    password: Mysql20170709
    driver-class-name: com.mysql.jdbc.Driver